---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-system
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: smithery
  namespace: demo-system
---
apiVersion: v1
kind: Service
metadata:
  name: smithery
  namespace: demo-system
spec:
  selector:
    app: smithery
  type: NodePort
  ports:
  - name: http
    port: 8081
    targetPort: http
    protocol: TCP
    nodePort: 30081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smithery
  namespace: demo-system
  labels:
    app: smithery
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: smithery
  template:
    metadata:
      labels:
        app: smithery
    spec:
      serviceAccountName: smithery
      containers:
      - name: smithery
        image: kind.local/smithery:latest
        #image: smithery:latest
        imagePullPolicy: Never
        args:
          - --debug=true
          - --port=8081
          - --authn-namespace=demo-system
        ports:
        - name: http
          containerPort: 8081
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: smithery
rules:
- apiGroups:
  - widgets.templates.krateo.io
  resources:
  - "*"
  verbs:
  - get
  - list
  - create
  - delete
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - create
  - delete
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  - configmaps
  - secrets
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: smithery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: smithery
subjects:
- kind: ServiceAccount
  name: smithery
  namespace: demo-system
